env:
  browser: true
  node: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:svelte/prettier
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
parserOptions:
  ecmaVersion: latest
  sourceType: module
